[package]
name = "grapple_pwd"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = ""
authors = ["grapple228 <greenapple228882@yandex.ru>"]
readme = "README.md"
repository = "https://github.com/grapple228/rust_grapple_pwd.git"

[lints.rust]
unsafe_code = "forbid"
unused = { level = "allow", priority = -1 } # For exploratory dev.

[dependencies]
# App Libs
grapple_utils = { version = "0.2", features = ["b64"] }

# Async
tokio = { version = "1", features = ["full"] }

# Crypt
argon2 = {version = "0.5", features = ["std"] }
rand = "0.8"

# Other
derive_more = {version = "1", features = ["from"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["fast-rng", "v4", "serde"] }
enum_dispatch = "0.3"
lazy-regex = "3"
log = "0.4.27"
constant_time_eq = "0.4.2"
hmac = "0.12.1"
sha2 = "0.10.9"
bytes = "1.11.1"

[dev-dependencies]
anyhow = "1"
